//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Id_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public string apellido_p { get; set; }
        public string apellido_m { get; set; }
        public Nullable<int> id_direccion { get; set; }
        public Nullable<int> telefono { get; set; }
        public string email { get; set; }
        public Nullable<int> id_tarjeta { get; set; }
        public int id_usuario { get; set; }
    }
}
