//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int id_direccion { get; set; }
        public string estado { get; set; }
        public string municipio { get; set; }
        public string ciudad { get; set; }
        public string codigo_postal { get; set; }
        public string telefono { get; set; }
        public string direccion_1 { get; set; }
        public string direccion_2 { get; set; }
    }
}
