//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paqueteria
    {
        public int id_paqueteria { get; set; }
        public string nombre_paqueteria { get; set; }
        public int telefono { get; set; }
        public string sitio_web { get; set; }
        public int rfc { get; set; }
        public string contacto { get; set; }
        public int telefono_contacto { get; set; }
    }
}
