//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion_producto { get; set; }
        public double precio { get; set; }
        public double coste { get; set; }
        public string imagen_producto { get; set; }
        public int id_categoria { get; set; }
        public System.DateTime ultima_actualizacion { get; set; }
        public int id_usuario { get; set; }
        public int id_marca { get; set; }
        public Nullable<int> id_producto_relacionado { get; set; }
        public int clave_unica { get; set; }
    }
}
