//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int id_tarjeta { get; set; }
        public int numTarjeta { get; set; }
        public int mes_vencimiento { get; set; }
        public int anio_vencimiento { get; set; }
        public string nombre_titular { get; set; }
        public Nullable<int> id_direccion { get; set; }
    }
}
